Backend/blog/urls.py
from django.urls import path 
from .views import (
    BlogHomePageView,
    PostDetailView,
)

app_name='blog'

urlpatterns = [
    path('', BlogHomePageView.as_view(), name='home'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail' ),
]

Backend/core/urls.py
from django.contrib import admin
from django.urls import include, path
from . views import(
    HomePageView, 
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  HomePageView.as_view(), name="home"),
    path('blog/', include('blog.urls',namespace= 'blog')),
]

Backend/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Post(models.Model):
    
    class PostObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')
        
    options=(
        ('draft','Draft'),
        ('published','Published'),
    )
        
    category= models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=255)
    excerpt= models.TextField(null=True)
    content=models.TextField()
    slug= models.SlugField(max_length=250, unique_for_date='published', null=False, unique=True)
    published = models.DateTimeField(default=timezone.now)
    author= models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    status= models.CharField(max_length=10, choices=options, default='draft')
    objects = models.Manager() # default manager
    postobjects = PostObjects() # custom manager 
    
class Meta:
    ordering=('-published',) 
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post= models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name= models.CharField(max_length=50)
    email= models.EmailField()
    content= models.TextField()
    publish= models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=True)
    
    class Meta:
        ordering=('publish',) 
    
    def __str__(self):
        return f"Comment by {self.name}"

Backend/blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from . models import Post

# Create your views here.

class BlogHomePageView(TemplateView):
    template_name="blog/index.html" 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.postobjects.all()
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post-detail.html'
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.objects.filter(slug= self.kwargs.get('slug'))
        return context
    

Backend/core/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'index.html'

Backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Blog</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

Backend/templates/blog/index.html
{% extends 'base.html' %}
{% block title %} Mi Blog - Blog {% endblock title %} 
{% block content%} 
Blog HomePage

{% for post in posts %}
<a href="{% url 'blog:post-detail' slug=post.slug %}">
{{ post.title }}
{{ post.excerpt|truncatechars:50}}
</a>
{% endfor %}

{% endblock content%}

Backend/templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content%} 
Post detail view

{{ post.title }}
{{ post.excerpt|truncatechars:50}}

{% endblock content%}

Backend/templates/index.html
{% extends 'base.html' %}
{% block title %} Mi Blog - HomePage {% endblock title %} 
{% block content%} 

<h1>Blog Page </h1>
<a href="{% url 'home'%}">
    HomePage
</a>
<a href="{% url 'blog:home'%}">
    Blog
</a>
{% endblock content%}